app1/urls.py
from django.urls import path
from . import views
from django.contrib import admin
app_name='app1'
urlpatterns=[
    path('',views.index,name='index'),
    path('cartable/',views.person,name='person'),
    path('cartable/<int:topic_id>/',views.persons_personal,name='persons'),
    path('new_person/',views.new_person,name='new_person'),
    path('expenses/',views.expenses,name='expenses'),
    path('new_expenses/',views.new_expenses,name='new_expenses'),
    path('add_comment/',views.add_comment,name='comment'),
    path('edit_person_bullet/<int:entry_id>/',views.edit_person_bullet,name='edit_person_bullet'),
    path('edit_expenses/<int:entry_id>/',views.edit_expenses,name='edit_expenses'),
    path('delete_person/<int:item_id>',views.delete_person,name='delete_person'),
    path('delete_expenses/<int:item_id>',views.delete_expenses,name='delete_expenses'),
    path('edit_person/<int:entry_id>/',views.edit_person,name='edit_person'),
    path('admin/',admin.site.urls,name='admin'),
    ]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('',include('app1.urls'))
]

users/urls.py
from django.urls import path,include
from . import views
app_name='users'
urlpatterns=[
    path('',include('django.contrib.auth.urls')),
    path('register/',views.register,name='register'),
]

app1/models.py
from django.db import models
from django.contrib.auth.models import User
class Person(models.Model):
    CHOICES=(('5','saturday'),('6','sunday'),('0','monday'),('1','tuesday'),('2','wednesday'),('3','thursday'),('4','friday'))
    captain=models.ForeignKey(User,on_delete=models.CASCADE)
    adminswitch=models.BooleanField(default=False)
    name=models.CharField(max_length=200)
    lastname=models.CharField(max_length=200)
    owe=models.IntegerField()
    bullet=models.IntegerField()
    week = models.TextField(max_length=20,choices=CHOICES,default="user")
    def __str__(self):
        return self.name + " " + self.lastname
class Expenses(models.Model):
    person=models.ForeignKey(User, on_delete = models.CASCADE)
    name=models.TextField()
    cost=models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    class Meta :
        verbose_name_plural='expenses'
    def __str__(self):
        return f"{self.name[:50]}..."
# Create your models here.
class Comment(models.Model):
    userpage=models.ForeignKey(User, on_delete = models.CASCADE)
    name=models.CharField(max_length=200)
    answer=models.TextField(default="null")
    text=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.text
class Ip(models.Model):
    ip=models.TextField(default=None)
    def __str__(self):
        return self.ip

app1/forms.py
from django import forms
from .models import Person,Expenses,Comment
class PersonForm(forms.ModelForm):
    class Meta :
        model=Person
        fields=['name','lastname','week']
        labels={'text':''}
class ExpensesForm(forms.ModelForm):
    class Meta :
        model=Expenses
        fields=['name','cost']
        labels={'text':''}
        widgets={'text':forms.Textarea(attrs={'cols':80})}
class CommentForm(forms.ModelForm):
    class Meta :
        model=Comment
        fields=['name','text']
        labels={'text':''}
        widgets={'text':forms.Textarea(attrs={'cols':80})}

app1/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Person,Expenses,Comment,Ip
from .forms import PersonForm,ExpensesForm,CommentForm
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from datetime import datetime
from django.db.models import Q
def index(request):
    def get_ip(request):
        address = request.META.get('HTTP_X_FORWARDED_FOR')
        if address :
            ip = address.split(',')[-1].strip()
        else : 
            ip = request.META.get('REMOTE_ADDR')
        return ip
    ip = get_ip(request)
    u = Ip(ip=ip)
    result = Ip.objects.filter(Q(ip__icontains=ip))
    if len(result) == 1:
        print(" user exist")
    elif len(result) > 1 :
        print("user exist more ...")
    else : 
        u.save()
        print("user is unique")
    count = Ip.objects.all().count()
    print("total user is ",count)
    context = {'count':count}
    return render(request,'app1/index.html',context)
@login_required
def person(request):                                                #persons list with expenses in cartable
    CHOICES={'5':'saturday','6':'sunday','0':'monday','1':'tuesday','2':'wednesday','3':'thursday','4':'friday'}
    person=Person.objects.filter(captain=request.user)
    comments=Comment.objects.filter(userpage=request.user)
    expenses=Expenses.objects.filter(person=request.user).order_by('date_added')
    dt = datetime.now()
    day=dt.weekday()
    duty_owner = 'null'
    for person_duty in person:
        if person_duty.week == str(day) :
            duty_owner = person_duty.name + " " + person_duty.lastname + " : today ( " + CHOICES[person_duty.week] + " )"
            break
    s=1
    x=[]
    for i in reversed(expenses):
        x.append(i)
        if(s>=5):
            break
        s=s+1
    content={'person':person,'expenses':x ,'comments':comments,'duty_owner':duty_owner}
    return render(request,'app1/person.html',content)
@login_required
def persons_personal(request,topic_id):                                      #page of a person in a captain group 
    person=get_object_or_404(Person,id=topic_id)
    weeks={'5':'saturday','6':'sunday','0':'monday','1':'tuesday','2':'wednesday','3':'thursday','4':'friday'}
    duty=weeks[person.week]
    if person.captain != request.user :
        raise Http404
    context={'person':person,'duty':duty}
    return render(request,'app1/persons_personal.html',context)
@login_required
def expenses(request):                                                  #page expenses
    expenses = Expenses.objects.filter(person=request.user).order_by('date_added')
    context={'expenses':expenses}
    return render(request,'app1/expenses.html',context)
@login_required
def new_person(request):
    persons=Person.objects.filter(captain=request.user)
    if request.method != 'POST' :
        form=PersonForm()
    else:
        form=PersonForm(data=request.POST)
        if form.is_valid():
            new_person=form.save(commit=False)
            for x in persons : 
                if new_person.week == x.week:
                    raise Http404
            new_person.captain=request.user
            new_person.adminswitch=False
            new_person.owe=0
            new_person.bullet=0
            new_person.save()
            messages.success(request, "The person has been successfully added . ")
            return redirect('app1:person')
    context={'form':form}
    return render(request,'app1/new_person.html',context)
@login_required
def new_expenses(request):
    expenses=Expenses.objects.filter(person=request.user).order_by('date_added')
    persons=Person.objects.filter(captain=request.user)
    number=Person.objects.filter(captain=request.user).count()
    if request.method !='POST':
          form=ExpensesForm()
    else:
        form=ExpensesForm(data=request.POST)
        if form.is_valid():
            new_entry =form.save(commit=False)
            costp = new_entry.cost / number
            new_entry.person=request.user
            for person in persons :
                if costp <= person.bullet :
                    person.bullet -= costp
                elif costp > person.bullet :
                    x= costp - person.bullet
                    person.bullet=0
                    person.owe+=x
                person.save()
            new_entry.save()
            messages.success(request, "The item has been successfully added . ")
            return redirect('app1:person')
    context={'expenses':expenses,'form':form}
    return render(request,'app1/new_expenses.html',context)
@login_required
def edit_expenses(request,entry_id):
    persons=Person.objects.filter(captain=request.user)
    expenses=Expenses.objects.get(id=entry_id)
    number=Person.objects.filter(captain=request.user).count()
    if request.method != 'POST' :
        form = ExpensesForm(instance=expenses)
    else:
        costfirst= expenses.cost / number
        form=ExpensesForm(instance=expenses,data=request.POST)
        if form.is_valid():
            formx=form.save(commit=False)
            cost_per_person = formx.cost / number           #hazine jadid bara har nafar
            print(costfirst,cost_per_person)
            if cost_per_person  > costfirst :               #age hazine afzayesh yaft
                costbetween = cost_per_person - costfirst         #ekhtelaf bein hazine ghabli va hazine jadid
                for person in persons :
                    if costbetween <= person.bullet :          #age mojoodi dasht
                        person.bullet = person.bullet - costbetween 
                    elif costbetween > person.bullet :        #age mojoodi nakafi bood
                        x= costbetween - person.bullet
                        person.bullet=0
                        person.owe = person.owe + x
                    person.save()
            elif cost_per_person  < costfirst :              #age hazine kam shod
                costbetween = costfirst - cost_per_person     #ekhtelaf bein hazine ghabli va hazine jadid         
                for person in persons :
                    if (person.owe > 0)and((costbetween-person.owe) >= 0) :   #age bedehkar bood va va ba mohasebat be bullet ham ezafe beshe
                        person.bullet = person.bullet + (costbetween-person.owe) #yani faghat az bedehi kam beshe va be bullet ezafe beshe
                        person.owe=0
                    elif person.owe == 0 :              #age bedehkar nabood be bulletesh ezafe beshe
                        person.bullet = person.bullet + costbetween
                    elif (person.owe > 0)and((person.owe-costbetween)>0) :   #age bedehkar bood kheili faghat bedehi kam beshe
                        person.owe = person.owe - costbetween
                    person.save()
            form.save()
            messages.success(request, "The item has been successfully updated . ")
            return redirect('app1:expenses')
    context={'expenses':expenses,'form':form}
    return render(request,'app1/edit_expenses.html',context)
@login_required
def edit_person_bullet(request,entry_id) :
    person=Person.objects.get(id=entry_id)
    if request.method == 'POST' :
            x=int(request.POST['num'])
            if (person.owe > 0) and (person.owe - x >= 0) :
                person.owe -= x
            elif (person.owe > 0) and (x-person.owe > 0) :
                person.bullet = person.bullet + (x - person.owe)
                person.owe=0
            elif person.owe == 0 :
                person.bullet += x
            person.save()
            messages.success(request, "The person's bullet has been successfully updated . ")
            return redirect('app1:person')
    context={'person':person}
    return render(request,'app1/edit_person_bullet.html',context)
@login_required
def edit_person(request,entry_id):
    persons=Person.objects.filter(captain=request.user)
    person=Person.objects.get(id=entry_id)
    if request.method != 'POST' :
        form=PersonForm(instance=person)
    else :
        form=PersonForm(instance=person,data=request.POST)
        if form.is_valid():
            editperson=form.save(commit=False)
            for x in persons : 
                if editperson.week == x.week:
                    raise Http404
            form.save()
            messages.success(request, "The person has been successfully updated . ")
            return redirect('app1:person')
    context={'person':person,'form':form}
    return render(request,'app1/edit_person.html',context)
@login_required
def delete_expenses(request,item_id):
    expenses=Expenses.objects.get(id=item_id)
    expenses.delete()
    messages.success(request, "The item has been successfully deleted !")
    return redirect('app1:person')
@login_required
def delete_person(request,item_id):
    person=Person.objects.get(id=item_id)
    if (person.adminswitch == False) :
        person.delete()
    elif(person.adminswitch == True) :
        raise Http404
    messages.success(request, "The person has been successfully deleted !")
    return redirect('app1:person')
@login_required
def add_comment(request):
    if request.method != 'POST' :
       form=CommentForm()
    else :
       form=CommentForm(data=request.POST) 
       if form.is_valid() :
          comment=form.save(commit=False)
          comment.userpage=request.user
          comment.save()
          messages.success(request, "Your comment sent seccessfully . ")
          return redirect('app1:person')
    content={'form':form}
    return render(request,'app1/add_comment.html',content)


     
# Create your views here.

app1/templates/app1/add_comment.html
{% extends "app1/base.html" %}
{% load bootstrap4 %}
{% block content %}
<p class="font-weight-bolder">Add a new comment : </p>
<form action="{% url 'app1:comment' %}" method="post" class="form font-weight-bolder">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button class="btn btn-primary btn-block text-center" name="submit">Add</button>
    {% endbuttons %}
</form>
{% endblock content %}

app1/templates/app1/base.html
{% load bootstrap4 %}
{% load static %}
<!doctype html>
<html lang="en">
   <head>
      <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
      <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
      <title>dormitory</title>
      {% bootstrap_css %}
      {% bootstrap_javascript jquery='full' %}
   </head>
   <body>
       <nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm mb-1 border fixed-top">
         <ul class="navbar-nav mr-3">
            <li class="nav-item">
               <a class="nav-link border rounded shadow font-weight-bold text-white" style="background-color: 	#ff944d;" href="{% url 'app1:index' %}">Main page</a>
            </li>
         </ul>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
         </button>
         <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav mr-2">
               <li class="nav-item font-weight-bolder text-dark">
                  <a class="nav-link " href="{% url 'app1:person' %}">Portal</a>
               </li>
            </ul>
            <ul class="navbar-nav mr-auto">
               <li class="nav-item font-weight-bolder text-dark">
                  <a class="nav-link " href="{% url 'app1:admin:login' %}">Admin</a>
               </li>
            </ul>
            <ul class="navbar-nav ml-auto font-weight-bold ">
               {% if user.is_authenticated %}
                  <li class="nav-item">
                     <span class="navbar-text">Hello , {{user.username}} .</span>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                  </li>
               {% else %}
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:register' %}">Register</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
               </li>
               {% endif %}
            </ul>
         </div>
       </nav>
       <main role="main" class="container-fluid sizemax mt-5 mb-4" >
         <div class="pb-2 mb-1">
            {% block page-header %}{% endblock page-header %}
         </div>
         <div style="font-family:eng2;">
            {% block content %}{% endblock content %}
         </div>
       </main>
       <div class="bg-dark rounded text-white lead strong" style="font-family:eng5;font-size:2vw;bottom:0;">
         <p>Welcome to our site and we are glad that you joined us.</p>
         <p >This site is a test and initial project, which is just a web programming exercise and is coded with HTML,
             CSS, JavaScript, Bootstrap and Backend Python language with Django framework. </p>
         <p class="small">Please let us know if you see a bug in order to improve and improve this site.</p>
         <p class="small">Thank you very much</p>
         <p>gmail:vahidkh6882@gmail.com</p>
       </div>
   </body>
</html>

app1/templates/app1/edit_expenses.html
{% extends "app1/base.html" %}
{% load bootstrap4 %}
{% block content %}
<p><a href="{% url 'app1:expenses' %}" >{{expenses}}</a></p>
<p class="font-weight-bolder">Edit Expenses: </p>
<form action="{% url 'app1:edit_expenses' expenses.id %}" method="post" class="form font-weight-bolder">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button class="btn btn-primary btn-block text-center" name="submit">Save Changes</button>
    {% endbuttons %}
</form>
{% endblock content %}

app1/templates/app1/edit_person.html
{% extends "app1/base.html" %}
{% load bootstrap4 %}
{% block content %}
<p><a href="{% url 'app1:person' %}" >{{user.username}}</a></p>
<p class="font-weight-bolder">edit person (personal information): </p>
<form action="{% url 'app1:edit_person' person.id %}" method="post" class="form font-weight-bolder">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button class="btn btn-primary btn-block text-center" name="submit">Save Changes</button>
    {% endbuttons %}
</form>
{% endblock content %}

app1/templates/app1/edit_person_bullet.html
{% extends "app1/base.html" %}
{% block content %}
<p class="mt-4 font-weight-bolder">Add Money to {{person.name}} {{person.lastname}} : </p>
<form class="form d-flex flex-column" action="{% url 'app1:edit_person_bullet' person.id %}" method="post">
    {% csrf_token %}
    <input class="form-control mb-4" type="number" name="num" method="POST" max="100000" min="5000" autofocus>
    <button name="submit" class="btn btn-primary text-center form-control mb-4"> save changes </button>
</form>
{% endblock content %}

app1/templates/app1/expenses.html
{% extends "app1/base.html" %}
{% load static %}
{% block content %}
{% if messages %}
    {% for message in messages %}
    <div class="container-fluid p-0 text-center font-weight-bold">
      <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert" >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="True">&times;</span>
        </button>
        {{ message }}
      </div>
    </div>
    {% endfor %}
{% endif %}
<div class="col">
    {% for x in expenses reversed %}
    <div class="card mb-2">
        <div class="card-header">
            <p>ITEM : {{x.name}}</p>
        </div>
        <div class="card-body">
            <p>You bought this item on {{x.date_added|date:'M d, Y H:i'}} for the price of {{x.cost}} tomans</p>
        </div>
        <div class="card-footer">
            <a class="btn btn-success"  href="{% url 'app1:edit_expenses' x.id  %}" class="btn btn-primary">Edit this item</a>
            <button class="btn btn-danger" data-toggle="modal" data-target="#modaldels{{x.id}}">delete expenses</button>
        </div>
    </div>
    <div class="modal fade" id="modaldels{{x.id}}">        
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4>Delete Item</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Are you sure to remove this row and this information ?!</p>
                </div>
                <div class="modal-footer">
                    <a  class="btn btn-danger" href="{% url 'app1:delete_expenses' x.id %}">delete expense</a>  
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    <p>No items</p>
    {% endfor %}
</div>
{% endblock content %}

app1/templates/app1/index.html
{% extends "app1/base.html" %}
{% load static %}
{% block content %}
{% if messages %}
    {% for message in messages %}
    <div class="container-fluid p-0 text-center font-weight-bold">
      <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert" >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="True">&times;</span>
        </button>
        {{ message }}
      </div>
    </div>
    {% endfor %}
{% endif %}
 <div class="border rounded shadow mt-3 mb-3 text-center" style="background-color:	 #e699ff;">
   <p class="display-4 text-center font-weight-bolder mt-3" style="font-size:6vw;">Project Of Kashmar Univercity Dormitory</p><p class="font-weight-bold">version 1.1  , visits  : {{count}}</p>
   <p class="font-weight-bold text-center" style="font-family:eng2;font-size:4vw;">programmer and the designer : VAHID KHAZAEI </p>
 </div>
 <a class="btn text-white shadow font-weight-bolder btn-block mb-4" data-toggle="tooltip" data-placement="right" style="background-color:#8B008B;" title="Hooray!" href="{% url 'users:register' %}" >register</a>
 <div class="carousel slide shadow" id="main" data-ride="carousel">
      <ul class="carousel-indicators" >
        <li class="active" data-target="#main" data-slide-to="0"></li>
        <li data-target="#main" data-slide-to="1"></li>
        <li data-target="#main" data-slide-to="2"></li>
      </ul>
      <div class="carousel-inner" style="overflow:hidden;height:70vw !important;">
          <div class="carousel-item active">
            <div class="card">
              <img src="{% static '101.jpg' %}" class="card-img-top" style="height:70vw !important;">
              <div class=" card-img-overlay d-flex justify-content-center flex-column text-center text-white">
                <p class="font-weight-bolder">Builder and Designer</p>
                <h5>
                  {% if user.is_authenticated %}
                  The programmer , designer and owner Of this website say "Hi <span class="font-weight-bolder">{{user.username}}</span> . Welcome to my website .<br>
                  I hope you find it useful "
                  {% else %}
                  The programmer , designer and owner Of this website say "Hi . Welcome to my website .<br>
                  I hope you find it useful "
                  {% endif %}
                </h5>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="card">
              <img src="{% static 'serv.png' %}"  class="card-img-top" style="height:70vw !important;">
            </div>
          </div>
          <div class="carousel-item">
            <div class="card">
              <img src="{% static 'OQCI8X0.jpg' %}"  class="card-img-top"  style="height:70vw !important;">
              <div class="card-img-overlay d-flex justify-content-center flex-column text-center text-white">
                <p class="font-weight-bolder">NEWS</p>
                <p>
                  This site was established on 1401/08/06 <br> and is for personal use at no cost
                </p>
              </div>
            </div>
          </div>
      </div>
      <a class="carousel-control-prev" href="#main" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
      </a>
      <a class="carousel-control-next" href="#main" data-slide="next">
        <span class="carousel-control-next-icon"></span>
      </a>
  </div>
    
  
{% endblock content %}

              

app1/templates/app1/new_expenses.html
{% extends "app1/base.html" %}
{% load bootstrap4 %}
{% block content %}
<p class="font-weight-bolder">add a new expenses : </p>
<form action="{% url 'app1:new_expenses' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button class="btn btn-primary btn-block text-center" name="submit">Add New Expenses</button>
    {% endbuttons %}
</form>
{% endblock content %}

app1/templates/app1/person.html
{% extends "app1/base.html" %}
{% block content %}
{% if messages %}
    {% for message in messages %}
    <div class="container-fluid p-0 text-center font-weight-bold">
      <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert" >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="True">&times;</span>
        </button>
        {{ message }}
      </div>
    </div>
    {% endfor %}
{% endif %}
    <p class="text-center display-4 mt-4" style="font-size:6vw;">Participants :</p>
    <div class="border-bottom border-dark mb-4"></div>
    <div class="col">
            <div class="row card-group font-weight-bolder d-flex justify-content-center" style="font-family:eng2;">
                {% for x in person %}
                <div class="card container-fluid shadow-lg m-2">
                    <div class="card-header">{{x}}</div>
                    <div class="card-body">
                        <p class="card-text">owe : {{x.owe}}</p>
                        <p class="card-text">bullet : {{x.bullet}}</p>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <a class="btn btn-info" href="{% url 'app1:persons' x.id %}">Show Details</a>
                        <button class="btn btn-danger" data-toggle="modal" data-target="#modaldel{{x.id}}">kick out</button>
                    </div>
                </div>
                <div class="modal fade" id="modaldel{{x.id}}" style="font-family:eng5;">        
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4>Delete Item</h4>
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                            </div>
                            <div class="modal-body">
                                <p>Are you sure to remove this row and this information ?!</p>
                            </div>
                            <div class="modal-footer">
                                <a class="btn btn-danger" href="{% url 'app1:delete_person' x.id %}">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% empty %}
                <div class="bg-danger rounded shadow">
                    <h3 class="text-center mt-4">no participant have been added</h3>
                </div>
                {% endfor %}
            </div>
            <p><a class="btn btn-lg btn-outline-success btn-block mt-4 font-weight-bolder shadow ml-auto" href="{% url 'app1:new_person' %}" >add new participant</a></p>
            <div class="text-white rounded shadow-sm" style="background-color:#800040;">
                <p class="text-center font-weight-bold" style="font-size:2vw;">Duty to clean and go shopping  {{duty_owner}}</p>
            </div>
            <p class="display-4 text-center" style="font-size:6vw;">Expenses</p>
            <div class="border-bottom mb-4 border-dark "></div>
            <div class="row d-flex flex-column " style="font-family:eng5;">
                    {% for y in expenses %}
                    <div class="card flex-fill mb-2 shadow-sm" style="font-family:eng2;">
                        <div class="card-header bg-white">
                            <button class="btn btn-block btn-info m-2 shadow-lg" data-toggle="collapse" data-target="#expense{{y.id}}">
                                <h3 style="font-size:4vw;">{{y}}</h3>
                            </button>
                       </div>
                    </div>
                    <div id="expense{{y.id}}" class="collapse" style="font-family:eng2;" >
                        <div class="card-body">
                            <p class="mb-3">The Cost Of This Item : {{y.cost}}</p>
                            <h3><a class="btn btn-primary" href="{% url 'app1:expenses' %}">see the page</a></h3>
                        </div> 
                    </div>
                    {% empty %}
                    <div class="container text-white bg-danger rounded shadow">
                        <h3 class="text-center font-weight-bolder m-4">no expenses have been added</h3>
                    </div>
                    {% endfor %}
            </div>
            <p><a class="btn btn-outline-success btn-lg btn-block mt-3 font-weight-bolder" href="{% url 'app1:new_expenses' %}">add new expenses</a></p>
            <p class="display-4 text-center" style="font-size:6vw;">comments</p>
            <div class="border-bottom border-dark"></div>
            <div class="col font-weight-bolder" style="font-family:eng2;">
                <div class="row"></div>
                {% for z in comments %}
                <div class="media border p-3 mt-3 mb-3 row">
                    <div class="media-body">
                        <h4 style="font-size:2vw;">{{z.name}} posted on {{z.date_added|date:'M d, Y H:i'}}</h4>
                        <p>{{z.text}}</p>
                        {% if z.answer != "null" %}
                        <div class="media p-3 jumbotron">
                            <div class="media-body">
                               <h4>answer from super user (admin) :</h4>
                               <p>{{z.answer}}</p>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
                {% empty %}
                <h3 class="m-4 text-center font-weight-bolder">no comments have been added</h3>
                {% endfor %}
            </div>
            <a class="btn btn-primary btn-lg btn-block font-weight-bolder" href="{% url 'app1:comment' %}">add comment</a>
    </div>
        <div class="row bg-light border mt-4"></div>
    </div>
    
{% endblock content %}

app1/templates/app1/persons_personal.html
{% extends "app1/base.html" %}
{% block content %}
{% if messages %}
    {% for message in messages %}
    <div class="container-fluid p-0 text-center font-weight-bold">
      <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert" >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="True">&times;</span>
        </button>
        {{ message }}
      </div>
    </div>
    {% endfor %}
{% endif %}
<div class="card shadow-lg mt-4">
	<div class=" card-header text-center display-3 shadow-sm font-weight-bold" style="font-size:4vw;">
		<p> {{person.name}} {{person.lastname}}</p>
	</div>
	<div class=" card-body font-weight-bolder ">
		<p>details:</p>
			<p>this person have <kbd> {{person.bullet}} </kbd> tomans in his bullet </p>
			<p>, he should pay <kbd> {{person.owe}} </kbd> tomans to the leader</p>
			<p>and he should do the duties on <kbd>{{duty}}</kbd> .</p>
	</div>
	<div class="card-footer d-flex justify-content-between ">
	    <a href="{% url 'app1:edit_person_bullet' person.id %}">edit bullet</a>
		<a href="{% url 'app1:edit_person' person.id %}">edit person</a>
	</div>
</div>
	  {% endblock content %}